" gvimrc
"
scriptencoding utf-8

colorscheme desert

set cmdheight=1
set showtabline=2 " タブを常に表示

set guioptions-=T " ツールバーを表示しない
set guioptions-=a " VisualModeをOS標準の範囲選択表示にしない

set guifont=Monaco:h16

"" 行間を開ける
set linespace=2


